name: Docker Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x # Substitua pela versão correta
        
    - name: Build Docker image
      run: docker build -t ${{ github.repository }}/minimalapi:latest .
      
    - name: Log into GitHub Packages
      run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      
    - name: Tag Docker image
      run: docker tag ${{ github.repository }}/minimalapi:latest ghcr.io/${{ github.repository }}/minimalapi:latest
      
    - name: Push Docker image to GitHub Packages
      run: docker push ghcr.io/${{ github.repository }}/minimalapi:latest






